server {
    listen 80;
    server_name api.ko2-oreilly.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.ko2-oreilly.com;

    ssl_certificate /etc/ssl/certs/ko2.crt;
    ssl_certificate_key /etc/ssl/private/ko2.key;

    location / {
        proxy_pass http://localhost:7000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
